2016-09-28 13:04:24,938 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 13:09:35,430 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 13:09:41,062 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2016-09-28 13:09:43,309 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2016-09-28 13:09:45,732 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.26s
2016-09-28 13:09:51,676 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2016-09-28 14:17:46,111 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 14:20:48,031 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 14:39:21,476 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 14:40:49,579 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0027.PRINTABLE_print_VATB2.gcode
2016-09-28 16:42:57,208 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0028.print_LOCK_A2.gcode
2016-09-28 17:12:46,792 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0028.print_LOCK_A2.gcode
2016-09-28 22:03:20,263 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0029.dbool_STAGE_B2.gcode
2016-09-28 22:04:21,724 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0029.dbool_STAGE_B2.gcode
2016-09-28 22:05:07,169 - octoprint.server.api - INFO - Performing command: sudo halt
2016-09-28 22:05:07,333 - octoprint.server - INFO - Shutting down...
2016-09-28 22:05:08,139 - octoprint.server - INFO - Goodbye!
2016-09-28 22:05:16,705 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2016-09-28 22:05:21,803 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2016-09-28 22:05:24,384 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2016-09-28 22:05:24,386 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2016-09-28 22:05:24,398 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2016-09-28 22:05:24,478 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2016-09-28 22:05:28,529 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2016-09-28 22:05:28,888 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2016-09-28 22:05:28,899 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2016-09-28 22:05:28,913 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2016-09-28 22:05:28,915 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2016-09-28 22:05:28,929 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2016-09-28 22:05:28,935 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2016-09-28 22:05:28,963 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2016-09-28 22:05:30,271 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2016-09-28 22:05:30,484 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from http://plugins.octoprint.org/plugins.json
2016-09-28 22:05:30,880 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2016-09-28 22:05:31,340 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.42s
2016-09-28 22:05:32,193 - octoprint.plugins.portlister - INFO - Port Lister () {}
2016-09-28 22:05:32,287 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2016-09-29 13:45:21,393 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'en', 'path': '/', 'base_url': 'http://hradec.no-ip.org:5000/'}
2016-09-29 13:45:31,136 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2016-09-29 13:45:34,177 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.43s
2016-09-29 13:45:39,389 - octoprint.util.pip - INFO - Found pip at /usr/sbin/pip, version is 8.1.2
2016-09-29 13:45:45,366 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2016-09-29 14:05:41,839 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3.gcode
2016-09-29 14:05:53,412 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3.gcode
2016-09-29 14:06:00,580 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 14:06:10,580 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 14:06:20,581 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 14:06:30,581 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 14:06:40,132 - octoprint.timelapse - WARNING - Could not render movie, got return code 1: [image2 @ 0x5551dc50] Could find no file with path '/home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-%d.jpg' and index in the range 0-4
/home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140600-%d.jpg: No such file or directory

2016-09-29 14:07:08,892 - octoprint.filemanager.analysis - INFO - Starting analysis of local:slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3.gcode
2016-09-29 14:07:24,150 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2016-09-29 14:07:24,153 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2016-09-29 14:07:31,806 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140731-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 14:07:37,118 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2016-09-29 14:07:39,813 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2016-09-29 14:07:41,775 - octoprint.timelapse - ERROR - Could not capture image /home/rhradec/.octoprint/timelapse/tmp/slapCube.0029.print_PHONE_CLIP_RIGHT1.print_PHONE_CLIP_RIGHT2.print_PHONE_CLIP_RIGHT3_20160929140731-0.jpg from http://hradec.no-ip.org:5001/?action=snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/timelapse.py", line 505, in _perform_capture
    r = requests.get(self._snapshot_url, stream=True)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2016-09-29 21:33:07,085 - octoprint.server.api - INFO - Performing command: sudo halt
2016-09-29 21:33:07,282 - octoprint.server - INFO - Shutting down...
2016-09-29 21:33:07,803 - octoprint.server - INFO - Goodbye!
2016-09-29 21:33:16,545 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2016-09-29 21:33:21,631 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2016-09-29 21:33:24,135 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2016-09-29 21:33:24,137 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2016-09-29 21:33:24,148 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2016-09-29 21:33:24,206 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2016-09-29 21:33:28,204 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2016-09-29 21:33:28,544 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2016-09-29 21:33:28,554 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2016-09-29 21:33:29,166 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2016-09-29 21:33:29,169 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2016-09-29 21:33:29,182 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2016-09-29 21:33:29,188 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2016-09-29 21:33:29,216 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2016-09-29 21:33:30,526 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2016-09-29 21:33:30,546 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2016-09-29 21:33:30,891 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2016-09-29 21:33:30,898 - octoprint.plugins.portlister - INFO - Port Lister () {}
2016-09-29 21:33:31,156 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.24s
2016-09-29 21:33:32,161 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
